### ISSUE TITLE
Error: Remove SD while printing process

### ISSUE THREAD

**Issue by andydev97** [NARUTOfzr/Neptune_3_Pro#70]
Hello,
While printing process, I tested to remove my sd card. On my display they write an chines message and the printer makes an signal ton beep. I restart my printer with sd card. Now all my settings are resetted.

**Comment by NARUTOfzr** [comment]
HI! Sorry for the late reply. The prompt Chinese should be some errors in UI display, thank you for your feedback. We should avoid removing SD card in printing, such operation is not reasonable.

**Comment by andydev97** [comment]
Yes that's right. I wanted to test it to check for bugs in the firmware.
