### ISSUE TITLE
Print > Files corrupts / merges filenames on SD card

### ISSUE THREAD

**Issue by chriskeeble** [NARUTOfzr/Neptune_3_Pro#82]
When viewing files to print on the SD card, in root folder, the filenames are corrupted - showing first 40 chars of file 1 filename, but then adding file 2 filename instead of showing the whole of file 1 filename.

Here are the 3 files as seen on the Neptune 3 Plus:

Screenshot of Neptune Screen
![image](https://github.com/NARUTOfzr/Neptune_3_Pro_Plus_Max/assets/1886467/4212595d-45dd-4d3f-bf27-440d868673ab)

Screenshot from Windows
![image](https://github.com/NARUTOfzr/Neptune_3_Pro_Plus_Max/assets/1886467/6f21fe11-4c2f-4a9a-bb3e-0ead094bfb8a)

- Firmware Version 1.2.5.1b
- UI Version V1.4.2 
(V1.4.2-1.x.5.1b - 20230520, V1.4.2-20230520)

(I love that we can now see the whole filename in this firmware, but each filename should be separate).

The problem appears to be that only the first 40 chars of file 1's filename is displayed, and then file 2's filename is displayed in the same block.

**Comment by hindsa-nabeel** [comment]
Try keeping file names less than 30 characters.
This problem is already reported (in Chinese) here: https://github.com/NARUTOfzr/Neptune_3_Pro_Plus_Max/issues/62

**Comment by chriskeeble** [comment]
> Try keeping file names less than 30 characters. This problem is already reported (in Chinese) here: #62

Thank you - that does appear to be the same bug.  I've also experienced freezing after pressing "Print" with some files, as you described, but I believe this is may be a different issue.

Thanks again.

**Comment by chriskeeble** [comment]
Duplicate of #62
