### ISSUE TITLE
Hier wird nichts mehr passieren oder?

### ISSUE THREAD

**Issue by andrewheeler82** [NARUTOfzr/Neptune_3_Pro#91]
Die Entwicklungskosten sind gedeckt der Markt mit neuen Produkten überschwemmt. Hier wird denke ich nichts mehr passieren und somit hat die Firmware ihren finalen Stand erreicht.
Falls nicht bitte Ticket wieder schließen 😉.

**Comment by T3rm1** [comment]
Es arbeitet keiner mehr. Wer soll das Ticket bitte schließen xD

**Comment by andrewheeler82** [comment]
Mimi
